spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: Agriculture
  datasource:
    url: jdbc:mysql://localhost:3306/agriculture
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true                 #开启了驼峰命名配置的开关

pagehelper:
  reasonable: true
  helper-dialect: mysql

file:
  upload-dir: D:/upload/

alipay:
  appId: 9021000144675090
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCJrit4Xw0Ya2852zi6LBPSxyyflOsENgaaH7zE6JEc8P/5ebCi6gnT3YMAVMtVLjvB/SeS1uNvfh7qcrZBCagGpjWGJWgMcdtRWe8SNSOjM0fS9MAweif7AwPSIFKAIY484yHWeyXPnahixQCgA6P9jCjErqkWyWC+yvTphrAGg8BiwFRGu/5mxiCBW3Z1IC2rq0vxkSVDJVv2gdZEZUbXpR+XD1M5BpD5A2NkyFQpq2H09ULD0SJgG6ylMecL9X4+o1R0PkofkDGpSOVFvLOC0cAfMznkWGlzhn2WvMAhXx33MoS7+BU3wLdQZyM4uVY+fF8oxSzsCJdRbxkQz38JAgMBAAECggEAVkckDJmcDjp9CAedw+UNQx/3kcVzhT8J4hmTZN3M2hMYhdDBZUY+hFsi1dlNVoLThdxLqVQqUFr7qrXaCmWvuwL7NaZJTssmwhMWoxVT0Ni44LTpnzddyIn6IfqJWKwug29ebBbd+f31YHfNzXiakq/7eE1vvszRaJ6s3Y6+zkVkDe97VX1u8aXsWODbchD+wl1/riDyWHOUw+5NfiryGA91rGj/RqNOzPETItkGwyalPzx24G984/wyJz59bbrxjYcbD8gDtY+YZcV2P0klyXyj/zEWGv6PyeQgVMBfHqNPju69RjeXMSCJBBPcI20C14qKetQpzBKB656Ihc+HtQKBgQDK8c1HgxydU1BevWxnUBqgkvVf/7QJEqxKT9B9ShFPcD69M5tZU1YGVedG00maHhvugFxBR/XA2EZt5abXptgOqko9sAxlvcV0tEL8IpYyFOu7809yxcDbcinCuy7cyZmLLlxHlRuR7ILvkxS+mWjIaxkbK4xvDrBj+8uFM0pw4wKBgQCtrITPbwyRMov901XXAcmmLwsYP3pup6f+IyrXIgg3Y8zARuZa4QEy/NJlEDtTyPD7k0FhzAD/YfCFi2i/S1TONLrGeXl5O3ePSfKuNUy1r67qiNK72u/HDPnBIRPNHuU7TaTjPchQZl1Wz6x9THJeXHB8jH+0hO8khFSknMKwIwKBgBJ2UOBykwXU8HjN7rCvXtzAwcXL80roAfh4rlTXih+Z7Hs12KoVpLvK0NFmo0l797qIvtvJehfjFPUmcTkpGnqrDznxbA9NZkspovZhBxzjPlbI2a9tQhA0oIvwj2DSjj9VJlv0up9ZzseQr9BvEFM7Ovt3yLzJr05JN8iUU+9VAoGAYOXRT77gnx45lwvTZ9t6e3rh0MyR7a0jAJr0awV02hqXgWvNWEUTmzQN2w88WpnRQju9jef5YoNtY8UNUzWfglFPKC9cQ/SW115lxSa9vtzfVcGy+dbEUyV9L3DaEGa9dOH0LkkpOxpx116VGW+Om/EtXYAyPDCzEIe4hgNkaEsCgYBq6g3vToF8P1wUMxTAty4QRopMHZmiphOKlVP0C2NJroHRlmI8TqEhVYitXAbrbqkAJVuYnHVNPZ/pnSMZfM8VGafkTTmc2tvGsjNWCFiLR6s24DT7L7fyZsaavKARsKFf8kE7SgUEWtTMX5XlBVNstvGqQbP/xFZ1R5KSzZytBw==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyC6t664pwPNoF5ftJfcdGSfXSsspbuEScFRw/PxRHWqiSb1C3c96vCT4zq3e0NkFlZdSKeCFT3VMHu2yY4S7TTFiL79NkpD/MvpMBgfb3nT7u9mgjBuLjv78ZC5GnPqaiYNi6SerT5IN7ep36L4eInn8A1wEICPY8CNvKo0I2mqbIKCD9xNYY6OdX4yEVUwWGMR705YC/Lya7eLu2OtiLXGxcIT+byhF6gPV2UyH0Y4d/BM9hmsP1EnaSwEcbBdC2E8Q4XgLY4e5S6JrZAy3usM27iOCg1JhmWLI8N9Oo7iDnCtqmOhKay6PS54yLDFT83hQ3X+StmtPKRhy2W86uwIDAQAB
  notifyUrl: http://nnagh4.natappfree.cc/alipay/notify
  returnUrl: http://localhost:5174/OrderLayout
  signType: RSA2
  charset: UTF-8
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
#logging:
#  level:
#    org.springframework: DEBUG
#  file:
#    name: logs/application.log


