spring:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: Agriculture
  datasource:
    url: jdbc:mysql://localhost:3306/agriculture
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true                 #开启了驼峰命名配置的开关

pagehelper:
  reasonable: true
  helper-dialect: mysql

file:
  upload-dir: D:/upload/




